language: node_js
node_js:
  - 'lts/*'
  - '8'
sudo: required
dist: trusty
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
script:
- npm run build
branches:
  only:
  - master
  - dev
